--- #YAML:1.0
name:                Embperl
version:             2.3.0
abstract:            Embed Perl code in HTML documents
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    File::Spec:                    0.8
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Gerald Richter <richter@dev.ecos.de>
